# -*- coding: utf-8 -*-
"""雲端運算期末專題

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gwtHbyS_hzZkQn6enfb0VwhJBZXYxQ_R
"""

!pip install openai==0.28
!pip install gradio pdfplumber pydub azure-ai-textanalytics azure-cognitiveservices-speech azure-cognitiveservices-vision-face openai

!pip install --upgrade gradio

!pip uninstall -y deepface opencv-python opencv-python-headless
!pip install deepface tf-keras
!pip install --force-reinstall opencv-python-headless==4.10.0.84

import os
import io
import tempfile
import numpy as np
import gradio as gr
import pdfplumber
from pydub import AudioSegment
from PIL import Image
import time
import requests
import json
import cv2
from deepface import DeepFace


# Azure Text Analytics
from azure.core.credentials import AzureKeyCredential
from azure.ai.textanalytics import TextAnalyticsClient

# Azure Speech SDK
import azure.cognitiveservices.speech as speechsdk

# OpenAI (Azure OpenAI endpoint)
import openai

INTERVIEW_CONTEXT = {
    "resume_text": "",
    "keywords": "",
    "entities": "",
    "questions": "",
    "answer_text": "",
    "emotion_log": [],   # 存每次表情分析結果
}

face_cascade = cv2.CascadeClassifier(
    cv2.data.haarcascades + "haarcascade_frontalface_default.xml"
)

# -----------------------------
# === Configuration (編輯或用環境變數) ===
# -----------------------------
# Azure OpenAI 設定
OPENAI_API_BASE = os.getenv("OPENAI_API_BASE", "YOUR_AZURE_OPENAI_ENDPOINT")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "YOUR_AZURE_OPENAI_KEY")
GPT_DEPLOYMENT_NAME = os.getenv("GPT_DEPLOYMENT_NAME", "gpt-4o")
DALLE_DEPLOYMENT_NAME = os.getenv("DALLE_DEPLOYMENT_NAME", "dall-e-3")

# Language (Text Analytics)
LANGUAGE_ENDPOINT = os.getenv("LANGUAGE_ENDPOINT", "YOUR_LANGUAGE_ENDPOINT")
LANGUAGE_KEY = os.getenv("LANGUAGE_KEY", "YOUR_LANGUAGE_KEY")

# Speech
SPEECH_KEY = os.getenv("SPEECH_KEY", "YOUR_SPEECH_KEY")
SPEECH_REGION = os.getenv("SPEECH_REGION", "japaneast")

# Face API
FACE_ENDPOINT = os.getenv("FACE_ENDPOINT", "YOUR_FACE_ENDPOINT")
FACE_KEY = os.getenv("FACE_KEY", "YOUR_FACE_KEY")

# -----------------------------
# === 初始化客戶端 ===
# -----------------------------

try:
    text_analytics_client = TextAnalyticsClient(endpoint=LANGUAGE_ENDPOINT, credential=AzureKeyCredential(LANGUAGE_KEY))
except Exception as e:
    text_analytics_client = None
    print("⚠️ 無法建立 TextAnalyticsClient：", e)

openai.api_type = "azure"
openai.api_base = OPENAI_API_BASE
openai.api_version = "2025-01-01-preview"
openai.api_key = OPENAI_API_KEY

try:
    speech_config = speechsdk.SpeechConfig(subscription=SPEECH_KEY, region=SPEECH_REGION)
except Exception as e:
    speech_config = None
    print("⚠️ 無法建立 SpeechConfig：", e)

# -----------------------------
# === PDF 上傳與文本擷取 ===
# -----------------------------
def extract_text_from_pdf(file_obj):
    if file_obj is None:
        return "", "未選擇 PDF 檔案。"
    try:
        with pdfplumber.open(file_obj) as pdf:
            text_pages = [page.extract_text() or "" for page in pdf.pages]
        full_text = "\n".join(text_pages).strip()
        if not full_text:
            return "", "PDF 無可提取文字或文字擷取失敗。"
        return full_text, "成功擷取文本。"
    except Exception as e:
        return "", f"PDF 擷取發生錯誤: {e}"

# -----------------------------
# === Azure Text Analytics 履歷分析 ===
# -----------------------------
def analyze_resume_with_azure(resume_text):
    if not resume_text:
        return [], []
    if text_analytics_client is None:
        return ["錯誤：Language client 未初始化"], []
    try:
        kp_result = text_analytics_client.extract_key_phrases(documents=[resume_text])
        key_phrases = kp_result[0].key_phrases if not kp_result[0].is_error else []
        ents_result = text_analytics_client.recognize_entities(documents=[resume_text])
        entities = []
        if not ents_result[0].is_error:
            for ent in ents_result[0].entities:
                if ent.category in ["Skill", "JobTitle", "Organization", "Person"]:
                    entities.append((ent.text, ent.category))
        return key_phrases, entities
    except Exception as e:
        return [f"文字分析錯誤: {e}"], []

# -----------------------------
# === Azure OpenAI 生成面試題 ===
# -----------------------------
def generate_interview_questions(keyphrases, entities, job_title="技術主管"):
    entity_str = ", ".join([f"{t} ({c})" for t, c in entities]) if entities else ""
    kp_str = ", ".join(keyphrases) if keyphrases else ""
    prompt = f"""
根據以下履歷資料，為應徵【{job_title}】職位的人設計 5 個面試問題（技術、行為、領導力各類型）。
關鍵詞：{kp_str}
實體：{entity_str}
請以一整個段落輸出，每題前綴 QN: 。
"""
    try:
        resp = openai.ChatCompletion.create(
            engine=GPT_DEPLOYMENT_NAME,
            messages=[
                {"role": "system", "content": "你是一位專業的 HR 經理與技術面試官。"},
                {"role": "user", "content": prompt}
            ],
            temperature=0.6,
            max_tokens=500
        )
        text = resp.choices[0].message.content.strip()
        # 去掉換行，整段文字
        return [text.replace("\n", " ")]
    except Exception as e:
        return [f"GPT 生成失敗: {e}"]

# -----------------------------
# === Azure TTS ===
# -----------------------------
def tts_text_to_audio_np(text):
    if not text or speech_config is None:
        return None
    try:
        speech_config.speech_synthesis_voice_name = "zh-CN-XiaoxiaoNeural"
        synthesizer = speechsdk.SpeechSynthesizer(speech_config=speech_config, audio_config=None)
        result = synthesizer.speak_text_async(text).get()
        if result.reason == speechsdk.ResultReason.SynthesizingAudioCompleted:
            audio_bytes = result.audio_data
            audio_np = np.frombuffer(audio_bytes, dtype=np.int16)
            return (16000, audio_np)
        else:
            return None
    except Exception as e:
        print("TTS 錯誤:", e)
        return None

# -----------------------------
# === Azure STT ===
# -----------------------------
def transcribe_gradio_audio(audio_tuple):
    if not audio_tuple:
        return "未錄製任何聲音。"
    samplerate, audio_np = audio_tuple
    if audio_np is None:
        return "錄音資料為空。"
    try:
        with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as f:
            temp_wav = f.name
        seg = AudioSegment(
            audio_np.tobytes(),
            frame_rate=samplerate,
            sample_width=audio_np.dtype.itemsize,
            channels=1
        )
        seg.export(temp_wav, format="wav")
        if speech_config is None:
            return "Speech config 未初始化，無法辨識。"
        speech_config.speech_recognition_language = "zh-TW"
        audio_cfg = speechsdk.audio.AudioConfig(filename=temp_wav)
        recognizer = speechsdk.SpeechRecognizer(speech_config=speech_config, audio_config=audio_cfg)
        result = recognizer.recognize_once_async().get()
        try:
            os.remove(temp_wav)
        except:
            pass
        if result.reason == speechsdk.ResultReason.RecognizedSpeech:
            return result.text
        else:
            cd = result.cancellation_details
            return f"辨識失敗: {cd.reason} {cd.error_details if hasattr(cd, 'error_details') else ''}"
    except Exception as e:
        return f"音訊處理錯誤: {e}"

# -----------------------------
# === Face API 分析 (偵測人臉) ===
# -----------------------------


last_call_time = 0
last_face_result = "⏳ 等待分析..."

def analyze_face(frame):
    print("DeepFace analyze_face running")
    global last_call_time, last_face_result
    now = time.time()

    # 每 1.5 秒分析一次（DeepFace 夠快）
    if now - last_call_time < 1.5:
        return last_face_result

    last_call_time = now

    try:
        if frame is None:
            last_face_result = "❌ 沒有影像"
            return last_face_result

        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        faces = face_cascade.detectMultiScale(
            gray,
            scaleFactor=1.3,
            minNeighbors=5,
            minSize=(60, 60)
        )

        if len(faces) == 0:
            last_face_result = "😶 未偵測到人臉"
            return last_face_result

        x, y, w, h = faces[0]
        face_roi = frame[y:y+h, x:x+w]

        last_face_result = "🧠 表情分析中..."

        result = DeepFace.analyze(
            img_path=face_roi,
            actions=["emotion"],
            enforce_detection=False
        )

        emo = result[0]["dominant_emotion"]
        emo_scores = result[0]["emotion"]

        nervous_score = (
            emo_scores["fear"] * 0.45 +
            emo_scores["sad"] * 0.30 +
            emo_scores["neutral"] * 0.15 +
            emo_scores["angry"] * 0.10
        )

        INTERVIEW_CONTEXT["emotion_log"].append({
            "time": time.strftime("%H:%M:%S"),
            "dominant": result[0]["dominant_emotion"],
            "nervous": round(nervous_score, 2)
        })
        last_face_result = f"🙂 情緒：{result[0]['dominant_emotion']}｜緊張度 {nervous_score:.1f}"


        return last_face_result

    except Exception as e:
        last_face_result = f"❌ 錯誤：{e}"
        return last_face_result



# ===========================================================
# 🔵 ① GPT 面試報告生成
# ===========================================================
def generate_final_report(resume, keywords, entities, questions, answer):
    ctx = INTERVIEW_CONTEXT

    emotion_summary = "無表情資料"
    if ctx["emotion_log"]:
        avg_nervous = sum(e["nervous"] for e in ctx["emotion_log"]) / len(ctx["emotion_log"])
        emotion_summary = (
            f"平均緊張度：{avg_nervous:.1f} / 100\n"
            f"最近紀錄：{ctx['emotion_log'][-5:]}"
        )

    prompt = f"""
你是一位資深技術面試官，請根據以下完整面試資料撰寫最終評估報告。

【履歷全文】
{resume}

【履歷關鍵字】
{keywords}

【履歷實體】
{entities}

【面試問題】
{questions}

【口述回答】
{answer}

【臉部表情與心理狀態分析】
{emotion_summary}

請輸出以下結構（禁止列表）：
📌 應徵者能力評分（0–100）
📌 技術能力分析
📌 溝通與心理穩定度分析（根據表情）
📌 優勢亮點
📌 需加強能力
📌 建議後續練習方向
📌 最終面試建議（錄用 / 觀望 / 不建議）
"""

    try:
        resp = openai.ChatCompletion.create(
            engine=GPT_DEPLOYMENT_NAME,
            messages=[
                {"role": "system", "content": "你是一位專業的技術面試官與 HR 顧問。"},
                {"role": "user", "content": prompt}
            ],
            temperature=0.5,
            max_tokens=900
        )
        return resp.choices[0].message.content.strip()

    except Exception as e:
        return f"❌ 生成失敗：{e}"


# ===========================================================
# 🔵 ② DALL·E 履歷視覺化生成
# ===========================================================

def generate_resume_visual(resume_text):
    # 1. 設定參數
    api_base = OPENAI_API_BASE.rstrip("/")
    api_key = OPENAI_API_KEY
    deployment_name = "dall-e-3"
    api_version = "2024-02-01"

    if not resume_text:
        return None

    # 2. 準備 Prompt (截斷以符合長度限制)
    safe_text = resume_text[:400].replace("\n", " ")
    prompt = f"Create a modern, clean, professional resume UI design layout. No text details, just visual structure. Context: {safe_text}"

    # 3. 拼接正確的 Azure URL
    # 格式: https://{ResourceName}.openai.azure.com/openai/deployments/{DeploymentName}/images/generations?api-version={Version}
    url = f"{api_base}/openai/deployments/{deployment_name}/images/generations?api-version={api_version}"

    headers = {
        "api-key": api_key,
        "Content-Type": "application/json"
    }

    body = {
        "prompt": prompt,
        "size": "1024x1024",
        "n": 1,
        "quality": "standard", # DALL-E 3 選項
        "style": "natural"     # DALL-E 3 選項
    }

    print(f"🎨 [Direct API] 正在請求: {url}")

    try:
        # 4. 直接發送 POST 請求
        response = requests.post(url, headers=headers, json=body)

        # 5. 檢查回應
        if response.status_code == 200:
            result = response.json()
            # 解析 Azure 回傳的 JSON 結構
            image_url = result['data'][0]['url']
            print("✅ 圖片生成成功！")
            return image_url
        else:
            # 印出錯誤代碼與訊息
            print(f"❌ API 請求失敗 [Code {response.status_code}]: {response.text}")
            return None

    except Exception as e:
        print(f"❌ 發生例外錯誤: {e}")
        return None
def sync_context_to_tab2():
    return (
        INTERVIEW_CONTEXT["keywords"],
        INTERVIEW_CONTEXT["entities"],
    )
def sync_context_to_ui():
    return (
        INTERVIEW_CONTEXT["resume_text"],
        INTERVIEW_CONTEXT["keywords"],
        INTERVIEW_CONTEXT["entities"],
        INTERVIEW_CONTEXT["questions"],
        INTERVIEW_CONTEXT["answer_text"],
    )



# -----------------------------
# === Gradio UI ===
# -----------------------------
def build_gradio_interface():
    with gr.Blocks(title="整合式：Resume → 分析 → 面試練習（Azure + OpenAI）") as demo:
        gr.Markdown("# Azure AI 虛擬面試官：多模態履歷分析與面試輔導系統")

        # Tab1: 上傳並分析履歷
        with gr.Tab("1. 上傳並分析履歷"):
            pdf_file = gr.File(label="上傳 PDF 履歷（.pdf）", file_types=[".pdf"])
            extract_btn = gr.Button("提取文本 & 分析")
            resume_textbox = gr.Textbox(label="擷取到的履歷純文本", lines=12)
            ka_output = gr.Textbox(label="關鍵字 (Key Phrases)", lines=6)
            entities_output = gr.Textbox(label="抽取到的實體 (Entity, Category)", lines=6)
            def run_extract_and_analyze(file_obj):
                if file_obj is None:
                    return "", "", "", "請上傳 PDF 檔案。"

                text, msg = extract_text_from_pdf(file_obj.name if hasattr(file_obj, 'name') else file_obj)
                if not text:
                    return "", "", "", msg

                kp, ents = analyze_resume_with_azure(text)
                ents_str = "; ".join([f"{t} ({c})" for t, c in ents]) if ents else ""
                kp_str = ", ".join(kp) if kp else ""

                # ⭐ 存進全域 Context
                INTERVIEW_CONTEXT["resume_text"] = text
                INTERVIEW_CONTEXT["keywords"] = kp_str
                INTERVIEW_CONTEXT["entities"] = ents_str


                return text, kp_str, ents_str, "分析完成。"
            extract_btn.click(run_extract_and_analyze, inputs=[pdf_file], outputs=[resume_textbox, ka_output, entities_output, gr.Textbox(visible=False)])

        # Tab2: 生成面試題 & TTS 播放
        with gr.Tab("2. 生成面試題 & TTS 播放"):
            kp_in = gr.Textbox(label="關鍵字", lines=2)
            ents_in = gr.Textbox(label="實體", lines=2)
            job_title = gr.Textbox(label="應徵職稱", value="技術主管")
            load_tab2_btn = gr.Button("🔄 載入履歷分析結果")

            load_tab2_btn.click(
                sync_context_to_tab2,
                inputs=[],
                outputs=[kp_in, ents_in]
            )
            gen_btn = gr.Button("生成面試問題")
            questions_box = gr.Textbox(label="生成的面試問題", lines=8)
            tts_btn = gr.Button("播放選中問題（TTS）")
            tts_audio = gr.Audio(label="TTS 音訊", type="numpy", interactive=False)
            def gen_questions(kp, ents, jt):
                kp_list = [k.strip() for k in kp.split(',') if k.strip()]
                ents_list = []
                for part in ents.split(';'):
                    part = part.strip()
                    if not part:
                        continue
                    if '(' in part and ')' in part:
                        t = part[:part.rfind('(')].strip()
                        c = part[part.rfind('(')+1:part.rfind(')')].strip()
                        ents_list.append((t, c))
                    else:
                        ents_list.append((part, ''))
                q = generate_interview_questions(kp_list, ents_list, job_title=jt)
                questions_text = "\n".join(q)

                # ⭐⭐⭐ 加在這裡 ⭐⭐⭐
                INTERVIEW_CONTEXT["questions"] = questions_text
                return "\n".join(q)
            gen_btn.click(gen_questions, inputs=[kp_in, ents_in, job_title], outputs=[questions_box])
            def tts_play_selected(questions_text):
                if not questions_text:
                    return None
                first_line = questions_text.splitlines()[0]
                return tts_text_to_audio_np(first_line)
            tts_btn.click(tts_play_selected, inputs=[questions_box], outputs=[tts_audio])



        # Tab3: 回答錄音 -> STT
        with gr.Tab("3. 回答錄音 (Record) → STT 辨識"):
            recorder = gr.Audio(sources=["microphone"], type="numpy", label="請錄下您的回答（點 Record）")
            transcribe_btn = gr.Button("轉文字 (STT)")
            transcription = gr.Textbox(label="辨識結果 (文字)")


            def transcribe_and_store(audio_tuple):
                result_text = transcribe_gradio_audio(audio_tuple)
                # ⭐⭐⭐ 加在這裡 ⭐⭐⭐
                INTERVIEW_CONTEXT["answer_text"] = result_text
                return result_text
            transcribe_btn.click(
                transcribe_and_store,
                inputs=[recorder],
                outputs=[transcription]
            )

    # Tab4: 臉部情緒分析
        with gr.Tab("4. 臉部情緒分析"):
            gr.Markdown("## 🎥 即時臉部分析（Azure + DeepFace）")

            webcam = gr.Image(
                sources=["webcam"],
                type="numpy",
                streaming=True,
                label="Webcam"
            )

            analysis_output = gr.Textbox(label="分析結果", lines=5)

            webcam.stream(
                analyze_face,
                inputs=webcam,
                outputs=analysis_output
            )


        # ======================================================
        # 🔵 Tab5：AI 自動生成最終面試報告
        # ======================================================
        with gr.Tab("5. 最終面試報告"):
            gr.Markdown("### 📑 自動彙整履歷 + 問題 + 回答 → 生成完整面試評估")

            input_resume = gr.Textbox(label="履歷文字", lines=6)
            input_keywords = gr.Textbox(label="關鍵字", lines=2)
            input_entities = gr.Textbox(label="實體資料", lines=2)
            input_questions = gr.Textbox(label="面試題目", lines=4)
            input_answer = gr.Textbox(label="面試口述回答(STT辨識結果)", lines=4)

            # ⭐ 新增同步按鈕 ⭐
            load_btn = gr.Button("🔄 載入目前面試資料")

            load_btn.click(
                sync_context_to_ui,
                inputs=[],
                outputs=[
                    input_resume,
                    input_keywords,
                    input_entities,
                    input_questions,
                    input_answer
                ]
            )

            report_btn = gr.Button("📄 生成面試報告")
            report_output = gr.Textbox(label="最終面試評分報告", lines=14)

            report_btn.click(
                generate_final_report,
                inputs=[
                    input_resume,
                    input_keywords,
                    input_entities,
                    input_questions,
                    input_answer
                ],
                outputs=[report_output]
            )


        # ======================================================
        # 🔵 Tab6：DALL·E 履歷視覺設計生成
        # ======================================================
        with gr.Tab("6. DALL·E 履歷視覺排版"):
            gr.Markdown("### 🎨 輸入履歷文字 → 自動生成美觀排版設計圖")

            resume_input = gr.Textbox(label="履歷全文", lines=12)
            load_tab6_btn = gr.Button("🔄 載入履歷內容")

            load_tab6_btn.click(
                lambda: INTERVIEW_CONTEXT["resume_text"],
                inputs=[],
                outputs=[resume_input]
            )
            dalle_btn = gr.Button("📌 生成設計視覺稿")
            dalle_img = gr.Image(label="生成圖像預覽")

            dalle_btn.click(generate_resume_visual, inputs=[resume_input], outputs=[dalle_img])


        gr.Markdown("---\n> Tips: 若想要串成完整面試流程，可以先在 Tab1 擷取並分析履歷，複製關鍵字/實體到 Tab2，生成題目並播放；使用 Tab3 錄音並轉文字；Tab4 即時分析面試者情緒;Tab5 對於你的面諭給出評分以及建議; Tab6幫您生成更好的履歷排版圖片供參考。")

    return demo

if __name__ == '__main__':
    demo = build_gradio_interface()
    demo.launch(server_name='0.0.0.0', debug=True)